# NUMPY

In [2]:
import numpy as np 

In [134]:
arr=np.array([1,3,474,5],np.int32)
arr

array([  1,   3, 474,   5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr[0]

1

In [6]:
arr[2]

47

In [7]:
arr[3]

5

In [8]:
myarr=np.array([[1,2,3,4,5],[6,7,9,4,10]])
myarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  9,  4, 10]])

In [9]:
myarr[0,1]

2

In [10]:
myarr[0,4]

5

In [11]:
myarr[1,2]

9

In [12]:
myarr.shape

(2, 5)

In [13]:
myarr.dtype

dtype('int32')

In [14]:


arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [15]:
myarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  9,  4, 10]])

In [16]:
myarr[0,3]=14

In [17]:
myarr

array([[ 1,  2,  3, 14,  5],
       [ 6,  7,  9,  4, 10]])

In [18]:
import numpy as n

arr1=n.array([11,23,45])

In [19]:
arr1

array([11, 23, 45])

In [20]:
newarr=np.array((1,3,4,5))
newarr

array([1, 3, 4, 5])

# Array Creation - Conversion from other python structures

**From LIST**

In [23]:
listarray = np.array([1,2,3,4])
listarray
listarray.dtype

dtype('int32')

**From TUPLE**

In [140]:
tup_array=np.array((1,2,3,4))
print(tup_array)

[1 2 3 4]


In [136]:
tuplearray = np.array(((1,4,5,6),(2,4,1,5)))
tuplearray

array([[1, 4, 5, 6],
       [2, 4, 1, 5]])

In [26]:
tuplearray.shape

(4,)

In [27]:
tuplearray.size

4

In [28]:
tuplearray.dtype

dtype('int32')

**From SET**

In [30]:
setarray = np.array({1,2,3,4})
setarray

array({1, 2, 3, 4}, dtype=object)

In [31]:
setarray.dtype

dtype('O')

# Array Creation - Intrinsic numpy array creation objects 

**zeros()**

In [34]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**ones()**

In [36]:
ones = np.ones((2,5))
print(ones)
ones.dtype

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


dtype('float64')

**arange()**

In [38]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

In [39]:
ar=np.array([1.0,2.0,3.0,4.0],np.float32)
ar.dtype

dtype('float32')

In [40]:
ar1=np.array([[1,2,3],[4,5,6],[4,5,7]])
ar1



array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 7]])

In [41]:
ar1.dtype

dtype('int32')

In [42]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
rng.dtype

dtype('int32')

**linspace**

In [142]:
lspace = np.linspace(1,5,5)
lspace

array([1., 2., 3., 4., 5.])

In [92]:
lspace[0]=7.0

In [94]:
lspace

array([7., 2., 3., 4., 5.])

In [46]:
lspace.dtype

dtype('float64')

**empty()**

In [110]:
emt = np.empty((3,2))
emt
emt.dtype

dtype('float64')

**empty_like()**

In [122]:
emt_like = np.empty_like(lspace)
emt_like

array([7., 2., 3., 4., 5.])

**identity()**

In [126]:
ide = np.identity(9)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [128]:
rng.shape

(15,)

In [130]:
lspace.shape

(5,)

In [134]:
ar1.shape

(3, 3)

***arange()_advanced***

In [145]:
arr = np.arange(36)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

***reshape()***

In [151]:
arr.reshape(2,18)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35]])

In [154]:
arr = np.arange(72)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

arr.reshape(6,12)

In [158]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# NUMPY AXIS

In [53]:
x = [[1,2,3],[4,5,6],[7,8,9]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
x[1][2]=10
x

[[1, 2, 3], [4, 5, 10], [7, 8, 9]]

In [55]:
x = np.array(x)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
x.shape

(3, 3)

In [23]:
x[1,1]=10
x

array([[ 1,  2,  3],
       [ 4, 10, 10],
       [ 7,  8,  9]])

In [57]:
x.sum()

45

In [59]:
x.sum(axis=1)

array([ 6, 15, 24])

In [61]:
x.max(axis=0)

array([7, 8, 9])

In [63]:
x.min(axis=1)

array([1, 4, 7])

In [65]:
x.max(axis=1)

array([3, 6, 9])

# Attributes

In [67]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [98]:
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr.flat

In [88]:
for i in arr:
    print(i)


[1 2 3]
[4 5 6]
[7 8 9]


In [90]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [96]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [104]:
arr.ndim

2

In [108]:
x=np.array([1,2,4])
x.ndim

1

In [140]:
#Check your array dimension
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [112]:
print(arr.size)
print(x.size)

9
3


In [114]:
print(arr.shape)
print(x.shape)

(3, 3)
(3,)


In [126]:
arr.nbytes

36

In [128]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
myarr = np.array([1,2,376,8])
myarr

array([  1,   2, 376,   8])

# Methods()

In [172]:
#1D array
arr1 = np.array([45,8,3])
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,10]])

**sort()**

In [163]:
# sorting on 1D array
arr1.sort()
arr1

array([ 3,  8, 45])

In [165]:
#sorting on 2D array
arr2.sort()
arr2

array([[ 3, 20, 52],
       [ 0,  7, 31],
       [10, 34, 88]])

**argmax()**

In [174]:
#argmax on 1D array
arr1.argmax()


0

In [176]:
#argmax() on 2D array
arr2.argmax()

7

**argmin()**

In [181]:
#1D array
arr1 = np.array([45,8,3])
arr1

array([45,  8,  3])

In [183]:
#argmin() on 1D array
arr1.argmin()

2

In [185]:
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,10]])
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88, 10]])

In [189]:
#argmin() on 2D array
arr2.argmin()

4

**argsort()**

In [208]:
#1D array
arr1 = np.array([45,8,3,45,2,99,1])
arr1

array([45,  8,  3, 45,  2, 99,  1])

In [210]:
#argsort() on 1D array
arr1.argsort()

array([6, 4, 2, 1, 0, 3, 5], dtype=int64)

In [202]:
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,3]])
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88,  3]])

In [206]:
#argsort() on 2D array
arr2.argsort()


array([[2, 0, 1],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

**argmax(axis=0)**

In [217]:
arr1 = np.array([45,8,3,45,2,99,1])
arr1

array([45,  8,  3, 45,  2, 99,  1])

In [213]:
#1D array
arr1.argmax(axis=0)

5

In [219]:
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,3]])
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88,  3]])

In [221]:
arr2.argmax(axis=0)

array([2, 2, 1], dtype=int64)

**argmin(axis=0)**

In [224]:
arr1 = np.array([45,8,3,45,2,99,1])
arr1

array([45,  8,  3, 45,  2, 99,  1])

In [228]:
arr1.argmin(axis=0)

6

In [230]:
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,3]])
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88,  3]])

In [232]:
arr2.argmin(axis=0)

array([0, 1, 0], dtype=int64)

**argmax(axis=1)**

In [239]:
arr2.argmax(axis=1)

array([1, 0, 1], dtype=int64)

In [241]:
arr2.argmin(axis=1)

array([2, 1, 2], dtype=int64)

**argsort(axis=0)**

In [244]:
arr1.argsort(axis=0)

array([6, 4, 2, 1, 0, 3, 5], dtype=int64)

In [246]:
arr2.argsort(axis=0)

array([[0, 1, 0],
       [1, 0, 2],
       [2, 2, 1]], dtype=int64)

In [248]:
arr2.argsort(axis=1)

array([[2, 0, 1],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)