# numpy_REVISION

In [1]:
import numpy as np

In [4]:
myarr = np.array([1,2,3,4])
print(type(myarr))

<class 'numpy.ndarray'>


In [6]:
myarr.shape

(4,)

In [8]:
myarr.reshape(2,-1)

array([[1, 2],
       [3, 4]])

In [10]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [18]:
arr.reshape(4,-1)

array([[1],
       [2],
       [3],
       [4]])

In [30]:
#Problem: Create a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20. Reshape the array to (5, 4) and then print it.

x = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr = np.array(x)
print("Before reshaping the array:\n ",arr)
print("After reshaping the array:\n ",arr.reshape(5,4))

Before reshaping the array:
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
After reshaping the array:
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [83]:
# Problem: Given the following 2D NumPy array, extract a subarray consisting of the 2nd and 3rd rows and the 1st and 2nd columns.

D2=[[45,6,23],[90,78,2],[22,18,0],[78,2,99]]
arr=np.array(D2)
print(arr[1:3,0:2])

[[90 78]
 [22 18]]


In [ ]:
#Problem: Create a 5x5 array with random integers between 1 and 10. Then, compute the mean, median, and standard deviation of the array.
import numpy as np

arr = np.random.randint(1, 11, size=(5, 5))

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Array:")
print(arr)
print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

# numpy Broadcasting 

In [101]:
""" rule no.1: dimensions must be same 
    rule no.2: if the dimensions are not same then check the demensions from right hand side
    if the first values from the both arrays right hand side is same then it can continue 
    or either of that right hand sidde value is one then it can continue otherwise break """

import numpy as np 

arr1 = np.array([1,2,4])#1D array
arr2= np.array([7,8,9])#1D array
print(arr1+arr2)#executed because both arrays had same dimensions

print()

arr1 = np.array([1,2,3])
arr2 = np.array([[4],[5],[6]])
print(arr1+arr2)#arr1.shape = (1 x 3) arr2.shape= (3 x 1) executed because one of the right hand side is 1 

print()


arr1=np.array([1,2,3])
arr2=np.array([[1,2,],[5,6],[7,8]])
print(arr1+arr2)#break because neither dimension is same nor the right hand side iss same or 1

print()

arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[5,6,7],[7,8,9]])
print(arr1+arr2)#executed because arr1=(1,3) and arr=(3,3) both right hand side is 3==3



[ 8 10 13]

[[5 6 7]
 [6 7 8]
 [7 8 9]]


[[ 2  4  6]
 [ 6  8 10]
 [ 8 10 12]]
