# NUMPY

In [2]:
import numpy as np 

In [3]:
arr=np.array([1,3,474,5],np.int32)
arr

array([  1,   3, 474,   5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr[0]

1

In [6]:
arr[2]

474

In [7]:
arr[3]

5

In [8]:
myarr=np.array([[1,2,3,4,5],[6,7,9,4,10]])
myarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  9,  4, 10]])

In [9]:
myarr[0,1]

2

In [10]:
myarr[0,4]

5

In [11]:
myarr[1,2]

9

In [12]:
myarr.shape

(2, 5)

In [13]:
myarr.dtype

dtype('int32')

In [14]:


arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [15]:
myarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  9,  4, 10]])

In [16]:
myarr[0,3]=14

In [17]:
myarr

array([[ 1,  2,  3, 14,  5],
       [ 6,  7,  9,  4, 10]])

In [18]:
import numpy as n

arr1=n.array([11,23,45])

In [19]:
arr1

array([11, 23, 45])

In [20]:
newarr=np.array((1,3,4,5))
newarr

array([1, 3, 4, 5])

# Array Creation - Conversion from other python structures

**From LIST**

In [23]:
listarray = np.array([1,2,3,4])
listarray
listarray.dtype

dtype('int32')

**From TUPLE**

In [25]:
tup_array=np.array((1,2,3,4))
print(tup_array)

[1 2 3 4]


In [26]:
tuplearray = np.array(((1,4,5,6),(2,4,1,5)))
tuplearray

array([[1, 4, 5, 6],
       [2, 4, 1, 5]])

In [27]:
tuplearray.shape

(2, 4)

In [28]:
tuplearray.size

8

In [29]:
tuplearray.dtype

dtype('int32')

**From SET**

In [31]:
setarray = np.array({1,2,3,4})
setarray

array({1, 2, 3, 4}, dtype=object)

In [32]:
setarray.dtype

dtype('O')

# Array Creation - Intrinsic numpy array creation objects 

**zeros()**

In [35]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**ones()**

In [37]:
ones = np.ones((2,5))
print(ones)
ones.dtype

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


dtype('float64')

**arange()**

In [39]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

In [40]:
ar=np.array([1.0,2.0,3.0,4.0],np.float32)
ar.dtype

dtype('float32')

In [41]:
ar1=np.array([[1,2,3],[4,5,6],[4,5,7]])
ar1



array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 7]])

In [42]:
ar1.dtype

dtype('int32')

In [43]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
rng.dtype

dtype('int32')

**linspace**

In [46]:
lspace = np.linspace(1,5,5)
lspace

array([1., 2., 3., 4., 5.])

In [47]:
lspace[0]=7.0

In [48]:
lspace

array([7., 2., 3., 4., 5.])

In [49]:
lspace.dtype

dtype('float64')

**empty()**

In [51]:
emt = np.empty((3,2))
emt
emt.dtype

dtype('float64')

**empty_like()**

In [53]:
emt_like = np.empty_like(lspace)
emt_like

array([7., 2., 3., 4., 5.])

**identity()**

In [55]:
ide = np.identity(9)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [56]:
rng.shape

(15,)

In [57]:
lspace.shape

(5,)

In [58]:
ar1.shape

(3, 3)

***arange()_advanced***

In [60]:
arr = np.arange(36)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

***reshape()***

In [62]:
arr.reshape(2,18)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35]])

In [63]:
arr = np.arange(72)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

arr.reshape(6,12)

In [65]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# NUMPY AXIS

In [68]:
x = [[1,2,3],[4,5,6],[7,8,9]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [69]:
x[1][2]=10
x

[[1, 2, 3], [4, 5, 10], [7, 8, 9]]

In [70]:
x = np.array(x)
x

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

In [71]:
x.shape

(3, 3)

In [72]:
x[1,1]=10
x

array([[ 1,  2,  3],
       [ 4, 10, 10],
       [ 7,  8,  9]])

In [73]:
x.sum()

54

In [74]:
x.sum(axis=1)

array([ 6, 24, 24])

In [75]:
x.max(axis=0)

array([ 7, 10, 10])

In [76]:
x.min(axis=1)

array([1, 4, 7])

In [77]:
x.max(axis=1)

array([ 3, 10,  9])

# Attributes

In [79]:
x

array([[ 1,  2,  3],
       [ 4, 10, 10],
       [ 7,  8,  9]])

In [80]:
x.T

array([[ 1,  4,  7],
       [ 2, 10,  8],
       [ 3, 10,  9]])

In [81]:
import numpy as np 
arr = np.array([[1, 2, 3],[4,5,6],[7,8,9]])

for x in arr.flat:
  print(x)


1
2
3
4
5
6
7
8
9


In [82]:
arr=np.array(x)
arr

array(9)

In [83]:
arr.flat

In [84]:
for i in arr.flat:
    print(i)

9


In [85]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [86]:
arr.ndim

2

In [87]:
x=np.array([1,2,4])
x.ndim

1

In [88]:
#Check your array dimension
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [89]:
print(arr.size)
print(x.size)

9
3


In [90]:
print(arr.shape)
print(x.shape)

(3, 3)
(3,)


In [91]:
arr.nbytes

36

In [92]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
myarr = np.array([1,2,376,8])
myarr

array([  1,   2, 376,   8])

**astype()- converts array from one  data type to another** 

In [95]:
var1 = np.array([[1,2,4],[3,5,6],[7,8,9]])
var1.astype(float)

array([[1., 2., 4.],
       [3., 5., 6.],
       [7., 8., 9.]])

# Methods()

In [97]:
#1D array
arr1 = np.array([45,8,3])
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,10]])

**sort()**

In [99]:
# sorting on 1D array
arr1.sort()
arr1

array([ 3,  8, 45])

In [100]:
#sorting on 2D array
arr2.sort()
arr2

array([[ 3, 20, 52],
       [ 0,  7, 31],
       [10, 34, 88]])

**argmax()**

In [102]:
#argmax on 1D array
arr1.argmax()


2

In [103]:
#argmax() on 2D array
arr2.argmax()

8

**argmin()**

In [105]:
#1D array
arr1 = np.array([45,8,3])
arr1

array([45,  8,  3])

In [106]:
#argmin() on 1D array
arr1.argmin()

2

In [107]:
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,10]])
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88, 10]])

In [108]:
#argmin() on 2D array
arr2.argmin()

4

**argsort()**

In [110]:
#1D array
arr1 = np.array([45,8,3,45,2,99,1])
arr1

array([45,  8,  3, 45,  2, 99,  1])

In [111]:
#argsort() on 1D array
arr1.argsort()

array([6, 4, 2, 1, 0, 3, 5], dtype=int64)

In [112]:
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,3]])
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88,  3]])

In [113]:
#argsort() on 2D array
arr2.argsort()


array([[2, 0, 1],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

**argmax(axis=0)**

In [115]:
arr1 = np.array([45,8,3,45,2,99,1])
arr1

array([45,  8,  3, 45,  2, 99,  1])

In [116]:
#1D array
arr1.argmax(axis=0)

5

In [117]:
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,3]])
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88,  3]])

In [118]:
arr2.argmax(axis=0)

array([2, 2, 1], dtype=int64)

**argmin(axis=0)**

In [120]:
arr1 = np.array([45,8,3,45,2,99,1])
arr1

array([45,  8,  3, 45,  2, 99,  1])

In [121]:
arr1.argmin(axis=0)

6

In [122]:
#2D array
arr2 = np.array([[20,52,3],[31,0,7],[34,88,3]])
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88,  3]])

In [123]:
arr2.argmin(axis=0)

array([0, 1, 0], dtype=int64)

**argmax(axis=1)**

In [125]:
arr2.argmax(axis=1)

array([1, 0, 1], dtype=int64)

In [126]:
arr2.argmin(axis=1)

array([2, 1, 2], dtype=int64)

**argsort(axis=0)**

In [128]:
arr1.argsort(axis=0)

array([6, 4, 2, 1, 0, 3, 5], dtype=int64)

In [129]:
arr2.argsort(axis=0)

array([[0, 1, 0],
       [1, 0, 2],
       [2, 2, 1]], dtype=int64)

In [130]:
arr2.argsort(axis=1)

array([[2, 0, 1],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

In [131]:
arr2.ravel()

array([20, 52,  3, 31,  0,  7, 34, 88,  3])

In [132]:
arr2

array([[20, 52,  3],
       [31,  0,  7],
       [34, 88,  3]])

In [133]:
arr2.reshape(9,1)

array([[20],
       [52],
       [ 3],
       [31],
       [ 0],
       [ 7],
       [34],
       [88],
       [ 3]])

In [134]:
new = np.array([[45,3,1],[56,33,90],[23,9,12]])
new

array([[45,  3,  1],
       [56, 33, 90],
       [23,  9, 12]])

In [135]:
new.reshape(9,1)

array([[45],
       [ 3],
       [ 1],
       [56],
       [33],
       [90],
       [23],
       [ 9],
       [12]])

In [136]:
arr1 = np.array([5,8,3,2,19,16])
arr1

array([ 5,  8,  3,  2, 19, 16])

In [137]:
arr1.argmin(axis=0)

3

In [138]:
arr1.argsort()

array([3, 2, 0, 1, 5, 4], dtype=int64)

In [139]:
arr2=np.array([[1,22,0],[16,5,33],[9,45,22]])
arr2

array([[ 1, 22,  0],
       [16,  5, 33],
       [ 9, 45, 22]])

In [140]:
arr2.argmin(axis=0)

array([0, 1, 0], dtype=int64)

In [141]:
arr2.argmin(axis=1)

array([2, 1, 0], dtype=int64)

In [142]:
arr2.argsort(axis=1)

array([[2, 0, 1],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

# W3 School --NUMPY-- 

***Getting Started***

In [145]:
#checking numpy version
import numpy as np
print(np.__version__)

1.25.2


**Creating array using _array()_ function***

In [147]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [148]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,45,67,89,34]])

print(arr[0:3, 2])

[ 3  8 67]


In [149]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


***Converting integer values to boolean***

In [151]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)


[ True False  True]
bool


***copy() and view()***

In [153]:
original_array= np.array([1,2,4,5])
original_array

array([1, 2, 4, 5])

In [154]:
carray = np.copy(original_array)
carray

array([1, 2, 4, 5])

In [155]:
carray[2]=6


In [156]:
print(original_array)
print(carray)

[1 2 4 5]
[1 2 6 5]


In [157]:
varray = original_array.view()


In [158]:
carrat=original_array.copy()

In [159]:
varray[3]=0

In [160]:
print(original_array)
print(varray)

[1 2 4 0]
[1 2 4 0]


***concatenate***

In [162]:
import numpy as np

In [163]:
#1D array concatenation
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [164]:
#2D array concatenation
ar1= np.array([[1,2],[3,4],[5,6]])
ar2= np.array([[1,2],[4,3],[6,3]])
np.concatenate((ar1,ar2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [4, 3],
       [6, 3]])

In [165]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.dtype

dtype('int32')

In [305]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr


array([1, 2, 3, 4, 5, 6])

In [303]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


***stack()***

In [366]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
#concatenate()

print(np.hstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))
print(np.concatenate((arr1,arr2)))
print(np.dstack((arr1,arr2)))


[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
[[[1 4]
  [2 5]
  [3 6]]

 [[4 7]
  [5 8]
  [6 9]]]


# reshape() - using 1D and 2D array 

In [167]:
#1D array to 2D array
arr1= np.array([1,2,3,4,5,6,7,8])
reshaped_arr=arr1.reshape(8,-1)
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# spliting NumPy array(array_split)

In [385]:
#1D splitting 
arr1 = np.array([1,2,3,4,5,6,7,8,9])
np.array_split(arr1,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [395]:
#2D spliting 

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# filter() 

In [408]:
arr1 = np.array([145,78,12,3,99,77,34])
filtered_array =[]
for i in arr1:
    if(i>40):
        filtered_array.append(True)
    else:
        filtered_array.append(False)

new_array=arr1[filtered_array]
new_array   

array([145,  78,  99,  77])

In [412]:
myarr = np.array([23,2,68,90,3,67,12])
filt_arr = []
for i in myarr:
    if(i%2==0):
        filt_arr.append(True)
    else:
        filt_arr.append(False)

new = myarr[filt_arr]
new

array([ 2, 68, 90, 12])

In [414]:
myarr = np.array([23,2,68,90,3,67,12])
filt_arr = []
for i in myarr:
    if(i%2==1):
        filt_arr.append(True)
    else:
        filt_arr.append(False)

new = myarr[filt_arr]
new

array([23,  3, 67])